name: Deploy Frontend

on:
  push:
    branches:
      - main # Sesuaikan nama branch kamu

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend # Fokus ke folder frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist # Folder hasil build
